###obtener todas las regiones
GET http://localhost:3000/api/region


@id = {{createRegion.response.body.data.id}}

### obtener una region
GET http://localhost:3000/api/region/{{id}}

### crear una nueva region
# @name createRegion
POST http://localhost:3000/api/region
Content-Type: application/json

{
  "name": "Arg",
  "description": "El pais mas pijudo"
}

### modificar una region (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/region/{{id}}
Content-Type: application/json

{
  "name": "Brasil",
  "description": "segundones"
}  

### modificar una region (PATCH - recurso parcial)
PATCH http://localhost:3000/api/region/{{id}}
Content-Type: application/json

{
  "description": "segundones x2"
}

### borrar una region
DELETE http://localhost:3000/api/region/{{id}}