###GET ALL
GET http://localhost:3000/api/inscription


@id = {{createInscription.response.body.data.id}}

###GET ONE
GET http://localhost:3000/api/inscription/{{id}}

###POST
# @name createInscription
POST http://localhost:3000/api/inscription
Content-Type: application/json

{
  "date": "2024-07-17",
  "status": "Approved",
  "competition": 1,
  "team": 1
}

###PUT
PUT http://localhost:3000/api/inscription/{{id}}
Content-Type: application/json

{
  "date": "2024-08-20",
  "status": "Pending",
  "competition": 1,
  "team": 1
}  

###PATCH
PATCH http://localhost:3000/api/inscription/{{id}}
Content-Type: application/json

{
  "status":"Rejected"
}

###DELETE
DELETE http://localhost:3000/api/inscription/{{id}}