###GET ALL
GET http://localhost:3000/api/inscriptions


@id = {{createInscriptions.response.body.data.id}}

###GET ONE
GET http://localhost:3000/api/inscriptions/{{id}}

###POST
# @name createInscriptions
POST http://localhost:3000/api/inscriptions
Content-Type: application/json

{
  "team": "Escuadron Salchichon",
  "state": "Approved"
}

###PUT
PUT http://localhost:3000/api/inscriptions/{{id}}
Content-Type: application/json

{
  "team": "Escuadron Maravilla",
  "state": "Pending"
}  

###PATCH
PATCH http://localhost:3000/api/inscriptions/{{id}}
Content-Type: application/json

{
  "team": "Scaloneta"
}

###DELETE
DELETE http://localhost:3000/api/inscriptions/{{id}}