###GET ALL
GET http://localhost:3000/api/news


@id = {{createNews.response.body.data.id}}

###GET ONE
GET http://localhost:3000/api/news/{{id}}

###POST
# @name createNews
POST http://localhost:3000/api/news
Content-Type: application/json

{
  "title": "Se perdio un caniche",
  "body": "A la vuelta de la esquina",
  "image": ""
}

###PUT
PUT http://localhost:3000/api/news/{{id}}
Content-Type: application/json

{
  "title": "Milei llega al 0,000000001% de inflacion",
  "body": "jugamos un lol?",
  "image": ""
}  

###PATCH
PATCH http://localhost:3000/api/news/{{id}}
Content-Type: application/json

{
  "body": "sentado en la esquina"
}

###DELETE
DELETE http://localhost:3000/api/news/{{id}}